<div class="ContentHeader"> 
	<h2>Adap.tv Code Of Conduct</h2>
</div>
<div class="contentpadding">

	 <h5>Partner Activities</h5>

                <p>In using the Services, Partner shall not, and shall not authorize or encourage any third party to</p>

                <ol>
                    <li>reverse engineer, decompile or disassemble any software components of the Services, or disseminate malware;</li>

                    <li>use the Services in a manner that violates any applicable government laws, rules and regulations, third parties&rsquo; proprietary rights, or any Adap.tv policies or in a manner that is deceptive, unethical, false, or misleading;</li>

                    <li>interfere or attempt to interfere with the proper working of the Services or any user&rsquo;s use of the Services or the full, complete, immediate and direct display of any Ads and any third-party websites accessed via links on Ads, or</li>

                    <li>engage in any deceptive or fraudulent activity as determined by Adap.tv in its sole discretion, which may include, without limitation, clicks without referring URLs, extraordinary high numbers of repeat clicks, fraudulent impressions generated by any person, robot, automated pro gram or similar device, or any clicks from non-approved root URLs.</li>
                </ol>
            
                <h5>ACCEPTABLE VIDEO PRACTICES</h5>
                <ol>
                    <li>Publishers are allowed a maximum of one video unit per page</li>

                    <li>There must be a 1:1 relationship between pre-roll video ad views and content views</li>

                    <li>We do not allow publishers to cycle multiple "pre-roll" ads before a single piece of content</li>

                    <li>eVAST tag only publishers must use our JS tag to verify domain at runtime</li>
                    <li>Video placements must conform exactly to the settings for the associated market placement in your account ie if a market placement is marked as supporting audio, then the video placement must not run muted</li>
                    <li>If publishers are using "playlist" functionality on their video player, then the content video in between the ad views must be at least 30 seconds long</li>
                    <li>Playlist functionality implies playing ads and content videos back to back with no end as long as the page is still open</li>
                </ol>
            
                <h5>UNACCEPTABLE METHODS FOR GENERATING IMPRESSIONS</h5>
                <ol>
                    <li>Adap.tv does not work with sites that generate traffic through pop-unders, regardless of our player is on the page being popped or not</li>

                    <li>Adap.tv requires publishers to run their placements only on domains that have been pre-approved by the Adap.tv</li>

                    <li>Adap.tv does not allow publishers to run placements that are hidden from the user in any way</li>

                    <li>Adap.tv does not allow publishers to load their site as an interstitial ad</li>
                    <li>Any video ad units running on a site must be fully visible to a user</li>
                                    </ol>
            
                <h5>PROHIBITED CONTENT</h5>
                <p>The Ads and Content on which the Partner uses the Services may not contain or link to any of the following categories of content ("Prohibited Content"):</p>
                <ol>
                    <li>content that is pornographic, obscene or indecent in nature or, in Adap.tv's sole and reasonable discretion, might be deemed harmful to Adap.tv's business reputation or the business reputation of Adap.tv's advertisers or partners;</li>

                    <li>content that promotes the excessive use of alcohol, tobacco or illegal substances, violence, profanity, expletives or inappropriate language;</li>

                    <li>content that offers or disseminates fraudulent goods, services, schemes, or promotions, including any make-money-fast or pyramid schemes;</li>

                    <li>content that promotes illegal activity such as copyright infringement, racism, hate, mail fraud, spam, pyramid schemes, or other advice not permitted under applicable law; or</li>
                    <li>content that has libelous and defamatory material, violates privacy rights, and/or is contrary to public policy or otherwise unlawful.</li>
                    
                </ol>
            
                <h5>PENALTIES FOR VIOLATING THE ADAP.TV MARKETPLACE CODE OF CONDUCT</h5>
                <ol>
                    <li>Adap.tv with withhold revenue for any impressions that were fraudulently generated, ran on unapproved sites, or which ran on unapproved content</li>

                    <li>If a publisher is found to have violated the code of conduct, all market placements will be immediately paused</li>

                    <li>Multiple violations will result in the permanent blacklisting of a URL from the Adap.tv Marketplace and the termination of your account</li>

                    
                </ol>
            
                <h5>MODIFICATIONS</h5>
                <p>Adap.tv reserves the right to update, change, revise, modify, and supplement the information within the Code of Conduct at any time. Partner will be notified when changes to the Code of Conduct are made through Partner's Account. Partner's continued use of the Services following the posting of such changes to the Code of Conduct will constitute Partner's acceptance of any such changes.</p>
            
        
    </div>